### ISSUE TITLE
Adopted for java 1.8

### ISSUE THREAD

**Issue by robertmakrytski** [DmitriiShamrikov/mslinks#23]
Can i adopt for 1.8 java and pull new branch?

**Comment by vatbub** [comment]
It should work with Java 1.8 out of the box, why would you want to adapt it?

**Comment by tresf** [comment]
I've been using this library with Java 1.8 for years as well.

**Comment by robertmakrytski** [comment]
i closed cas i can found proper dependency form your git
<dependency>
	<groupId>com.github.vatbub</groupId>
	<artifactId>mslinks</artifactId>
	<version>1.0.3.1</version>
</dependency>
i used not proper dependency

**Comment by vatbub** [comment]
@robertmakrytski I just had another look at it: You can use version 1.0.5 which is the latest version that is compatible with Java 1.8. The latest version (version 1.0.6.1) requires Java 10.
