### ISSUE TITLE
can't install

### ISSUE THREAD

**Issue by robertmakrytski** [DmitriiShamrikov/mslinks#24]
`Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project mslinks: Fatal error compiling`
![image](https://user-images.githubusercontent.com/10616325/106614222-1ce43500-657c-11eb-8a9c-d9d8c2f369cc.png)

**Comment by vatbub** [comment]
Can you maybe paste the entire build log?

**Comment by robertmakrytski** [comment]
i closed cas i can found proper dependency form your git
<dependency>
	<groupId>com.github.vatbub</groupId>
	<artifactId>mslinks</artifactId>
	<version>1.0.3.1</version>
</dependency>
i used not proper dependency
