### ISSUE TITLE
Dependencies resolution

### ISSUE THREAD

**Issue by jflefebvre06** [DmitriiShamrikov/mslinks#28]
Hello,

**https://dl.bintray.com** is no longer available

`[ERROR] Failed to execute goal on project ant: Could not resolve dependencies for project com.wac.core:ant:jar:0.0.1-SNAPSHOT: Failed to collect dependencies at com.github.vatbub:mslinks:jar:1.0.6.1: Failed to read artifact descriptor for com.github.vatbub:mslinks:jar:1.0.6.1: Could not transfer artifact com.github.vatbub:parentPom:pom:2.0.1-alpha2 from/to bintray-vatbub-fokprojectsReleases (https://dl.bintray.com/vatbub/fokprojectsReleases): Authorization failed for https://dl.bintray.com/vatbub/fokprojectsReleases/com/github/vatbub/parentPom/2.0.1-alpha2/parentPom-2.0.1-alpha2.pom 403 Forbidden -> [Help 1]`

**Comment by vatbub** [comment]
I know, I'm working on it

**Comment by vatbub** [comment]
In the meanwhile, feel free to clone my fork (GitHub.com/vatbub/mslinks) and run `mvn install`

**Comment by vatbub** [comment]
You can find the parent pom in Github.com/vatbub/defaultrepo

**Comment by vatbub** [comment]
I just published a new version on Maven Central, version `1.0.6.2` which has no dependencies whatsoever. Here are the coordinates for that:
```
<dependency>
  <groupId>com.github.vatbub</groupId>
  <artifactId>mslinks</artifactId>
  <version>1.0.6.2</version>
</dependency>
```

Keep in mind that it might take a couple of minutes for the new version to appear for download.

**Comment by vatbub** [comment]
For the rare folks who still use Java 7/8, here's your fix:
```xml
<dependency>
	<groupId>com.github.vatbub</groupId>
	<artifactId>mslinks</artifactId>
	<version>1.0.5.1</version>
</dependency>
```

**Comment by jflefebvre06** [comment]
Thanks !
