### ISSUE TITLE
ShellLinkHelper support for adding arguments

### ISSUE THREAD

**Issue by sterpumihai** [DmitriiShamrikov/mslinks#32]
The following method needs to be added to the ShellLinkHelper so target arguments are supported:

`	public void setArgs(String args)
	{
	  link.setCMDArgs(args);
	}`

**Comment by DmitriiShamrikov** [comment]
You can get ShellLink instance from the helper using `getLink()` method and set CMD arguments directly. Duplicating interface of ShellLink is not the purpose of the helper.
