### ISSUE TITLE
JDK11 Compat

### ISSUE THREAD

**Issue by tresf** [DmitriiShamrikov/mslinks#33]
Hi,

Thanks for this fantastic library. :)

The [latest mslinks release](https://github.com/DmitriiShamrikov/mslinks/releases/tag/1.0.7) fails any dependant project that is built with JDK11, the error is as follows:

```
    [javac] import mslinks.ShellLink;
    [javac]               ^
    [javac]   bad class file: /home/runner/work/tray/tray/lib/mslinks-1.0.7.jar(/mslinks/ShellLink.class)
    [javac]     class file has wrong version 58.0, should be 55.0
    [javac]     Please remove or make sure it appears in the correct subdirectory of the classpath.
```

Personally, for historical purposes, I've kept JDK8 level compatible with most of my project.  I could probably move permanently to JDK11 but the above suggests JDK13 which will break a lot of projects requiring this library (including my own)

Was this change intended?

**Comment by DmitriiShamrikov** [comment]
I don't mind JDK 11 compatibility. See 1.0.8 release
